CREATE DATABASE EVENT MANAGEMENT;
USE DATABASE;
CREATE TABLE USER(
UID INT NOTNULL AUTO-INCREMENT PRIMARY KEY
USERNAME VARCHAR(30),
PASSWORD VARCHAR9(30),
ADMIN BOOLEAN);
INSERT INTO USERS(USERNAME,PASSWORD,ADMIN)
VALUES(admin,admin,true)
CREATE TABLE ISSUED(
IID INT NOT NULL AUTO_INCREMENT
PRIMARY,
UID INT,
BID INT, 
ISSUED_DATE VARHAR(20), 
RETURN_DATE VARCHAR(20),
PERIOD INT,FINE INT);

CREATE TABLE BOOKING(BID INT NOT NULL AUTO _INCREMENT PRIMARY KEY,
 BDATE VARCHAR(40),
 PERIOD INT,
FINE INT);